// packages/vue/examples/components/add-user.vue
<script setup lang="ts">
import { PromiseComponentProps } from '@promise-components/vue'
import { reactive } from 'vue'

interface UserItem {
  name: string
  age: number
  id: number
}

/**
 * 🔴 The Props parameter must inherit from PromiseComponentsProps
 */
interface Props extends PromiseComponentProps<UserItem> {
  user?: UserItem
}

const props = defineProps<Props>()

const formData = reactive<UserItem>({
  name: '',
  age: 0,
  id: Math.random(),
  ...props.user, // If editing, fill in the default value
})

function handleSubmit () {
  if (!formData.name) return alert('Please enter `Name`')
  if (!formData.age) return alert('Please enter `Age`')

  // 🔴 Call resolve callback
  props.resolve(formData)
}

function handleCancel () {
  // 🔴 Call reject callback
  props.reject()
}
</script>

<template>
  <dialog open>
    <h2>Vue dialog</h2>

    <form>
      <p>
        <span>Name: </span>
        <input v-model="formData.name" type="text"/>
      </p>

      <p>
        <span>Age: </span>
        <input v-model="formData.age" type="number" min={0}/>
      </p>
    </form>

    <p>
      <button @click="handleCancel">Cancel</button>
      <button @click="handleSubmit">Submit</button>
    </p>
  </dialog>
</template>

// packages/react/examples/components/add-user.tsx
import { PromiseComponent, PromiseComponentProps } from '@promise-components/react'
import { FormEvent, useState } from 'react'

export interface UserItem {
  name: string
  age: number
  id: number
}

/**
 * 🔴 The Props parameter must inherit from PromiseComponentsProps
 */
interface Props extends PromiseComponentProps<UserItem> {
  user?: UserItem
}

/**
 * 🔴 Create a PromiseComponent instance
 */
export const AddUser = new PromiseComponent((props: Props) => {
  const [formData, setFormData] = useState(() => {
    return {
      name: '',
      age: 0,
      id: Math.random(),
      ...props.user, // If editing, fill in the default value
    }
  })

  function handleSubmit () {
    if (!formData.name) return alert('Please enter `Name`')
    if (!formData.age) return alert('Please enter `Age`')

    // 🔴 Call resolve callback
    props.resolve(formData)
  }

  function handleCancel () {
    // 🔴 Call reject callback
    props.reject()
  }

  function handleInput (key: keyof UserItem) {
    return (evt: FormEvent) => {
      setFormData({
        ...formData,
        [key]: evt.target.value
      })
    }
  }

  return (
    <dialog open>
      <h2>React dialog</h2>

      <form>
        <p>
          <span>Name: </span>
          <input value={formData.name} onInput={handleInput('name')} type="text"/>
        </p>

        <p>
          <span>Age: </span>
          <input value={formData.age} onInput={handleInput('age')} type="number" min={0}/>
        </p>
      </form>

      <p>
        <button onClick={handleCancel}>Cancel</button>
        <button onClick={handleSubmit}>Submit</button>
      </p>
    </dialog>
  )
})
