// packages/react/examples/components/user-list.tsx
import { useState } from 'react'
import { AddUser } from './add-user.tsx'

interface UserItem {
  name: string
  age: number
  id: number
}

export function UserList () {
  const [userList, setUserList] = useState<UserItem[]>([])

  async function handleAdd () {
    /**
     * 🔴 Using component
     */
    const newUser = await AddUser.render()

    setUserList((prevList) => [...prevList, newUser])
  }

  async function handleEdit (editIndex: number) {
    /**
     * 🔴 Using component and providing parameters (Edit mode)
     */
    const modifiedUser = await AddUser.render({
      user: userList[editIndex],
    })

    setUserList((prevList) => {
      return prevList.map((item, index) => {
        return index === editIndex ? modifiedUser : item
      })
    })
  }

  return (
    <div>
      <ul>{
        userList.map((item, index) => (
          <li key={item.id}>
            <span>Name: {item.name}, Age: {item.age}</span>
            <button onClick={() => handleEdit(index)}>Edit</button>
          </li>
        ))
      }</ul>

      <button onClick={handleAdd}>Add</button>
    </div>
  )
}

// packages/vue/examples/components/user-list.vue
<script setup lang="ts">
import { ref } from 'vue'
import { AddUser } from './add-user.promise.ts'

interface UserItem {
  name: string
  age: number
  id: number
}

const userList = ref<UserItem[]>([])

async function handleAdd () {
  /**
   * 🔴 Using component
   */
  const newUser = await AddUser.render()

  userList.value.push(newUser)
}

async function handleEdit (editIndex: number) {
  const target = userList.value[editIndex]

  /**
   * 🔴 Using component and providing parameters (Edit mode)
   */
  const modifiedUser = await AddUser.render({
    user: target,
  })

  Object.assign(target, modifiedUser)
}
</script>

<template>
  <div>
    <ul>
      <li v-for="(item, index) in userList" :key="item.id">
        <span>Name: {{ item.name }}, Age: {{ item.age }}</span>
        <button @click="handleEdit(index)">Edit</button>
      </li>
    </ul>

    <button @click="handleAdd">Add</button>
  </div>
</template>
